name: 🐞Bug report
description: There's a bug I want to report
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Do not use this form to ask questions or make suggestions; use the [appropriate](https://github.com/panva/fetch-message-signatures/issues/new/choose) Discussions topic for those.
  - type: textarea
    attributes:
      label: What happened?
      description:
        A clear and concise description of the bug and what you expected to happen instead.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What exact version of the library do you use?
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Runtime
      description: What runtime are you seeing the problem on?
      options:
        - Select an option
        - Browser
        - Bun
        - Cloudflare Workers
        - Deno
        - Electron
        - Node.js
        - Other (I will specify below)
    validations:
      required: true
  - type: input
    attributes:
      label: Runtime details
      description:
        Runtime version, browser vendor and version, operating system, and cryptographic provider.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code to reproduce
      description: Please provide a minimal, complete reproduction with keys and secrets replaced.
      render: js
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label:
            I have searched the issue tracker and discussions for similar topics and could not find
            anything related.
          required: true
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/panva/fetch-message-signatures/blob/main/CODE_OF_CONDUCT.md).
          required: true
