// Generated by `node --run fixtures`. Do not edit.
//
// Imports the vendored httpwg/structured-field-tests corpus as JSON modules, so that the test
// suite needs no filesystem and runs unchanged in every target runtime.

import metadata from './structured-field-tests/metadata.json' with { type: 'json' }
import f_binary_json from './structured-field-tests/binary.json' with { type: 'json' }
import f_boolean_json from './structured-field-tests/boolean.json' with { type: 'json' }
import f_date_json from './structured-field-tests/date.json' with { type: 'json' }
import f_dictionary_json from './structured-field-tests/dictionary.json' with { type: 'json' }
import f_display_string_json from './structured-field-tests/display-string.json' with { type: 'json' }
import f_examples_json from './structured-field-tests/examples.json' with { type: 'json' }
import f_item_json from './structured-field-tests/item.json' with { type: 'json' }
import f_key_generated_json from './structured-field-tests/key-generated.json' with { type: 'json' }
import f_large_generated_json from './structured-field-tests/large-generated.json' with { type: 'json' }
import f_list_json from './structured-field-tests/list.json' with { type: 'json' }
import f_listlist_json from './structured-field-tests/listlist.json' with { type: 'json' }
import f_number_generated_json from './structured-field-tests/number-generated.json' with { type: 'json' }
import f_number_json from './structured-field-tests/number.json' with { type: 'json' }
import f_param_dict_json from './structured-field-tests/param-dict.json' with { type: 'json' }
import f_param_list_json from './structured-field-tests/param-list.json' with { type: 'json' }
import f_param_listlist_json from './structured-field-tests/param-listlist.json' with { type: 'json' }
import f_string_generated_json from './structured-field-tests/string-generated.json' with { type: 'json' }
import f_string_json from './structured-field-tests/string.json' with { type: 'json' }
import f_token_generated_json from './structured-field-tests/token-generated.json' with { type: 'json' }
import f_token_json from './structured-field-tests/token.json' with { type: 'json' }
import f_serialisation_tests_key_generated_json from './structured-field-tests/serialisation-tests/key-generated.json' with { type: 'json' }
import f_serialisation_tests_number_json from './structured-field-tests/serialisation-tests/number.json' with { type: 'json' }
import f_serialisation_tests_string_generated_json from './structured-field-tests/serialisation-tests/string-generated.json' with { type: 'json' }
import f_serialisation_tests_token_generated_json from './structured-field-tests/serialisation-tests/token-generated.json' with { type: 'json' }

export const CORPUS_METADATA = metadata as {
  readonly repository: string
  readonly commit: string
  readonly committed: string
  readonly files: number
}

export const PARSE_FIXTURES: ReadonlyArray<readonly [name: string, cases: ReadonlyArray<unknown>]> = [
  ['binary.json', f_binary_json],
  ['boolean.json', f_boolean_json],
  ['date.json', f_date_json],
  ['dictionary.json', f_dictionary_json],
  ['display-string.json', f_display_string_json],
  ['examples.json', f_examples_json],
  ['item.json', f_item_json],
  ['key-generated.json', f_key_generated_json],
  ['large-generated.json', f_large_generated_json],
  ['list.json', f_list_json],
  ['listlist.json', f_listlist_json],
  ['number-generated.json', f_number_generated_json],
  ['number.json', f_number_json],
  ['param-dict.json', f_param_dict_json],
  ['param-list.json', f_param_list_json],
  ['param-listlist.json', f_param_listlist_json],
  ['string-generated.json', f_string_generated_json],
  ['string.json', f_string_json],
  ['token-generated.json', f_token_generated_json],
  ['token.json', f_token_json],
]

export const SERIALISATION_FIXTURES: ReadonlyArray<readonly [name: string, cases: ReadonlyArray<unknown>]> = [
  ['serialisation-tests/key-generated.json', f_serialisation_tests_key_generated_json],
  ['serialisation-tests/number.json', f_serialisation_tests_number_json],
  ['serialisation-tests/string-generated.json', f_serialisation_tests_string_generated_json],
  ['serialisation-tests/token-generated.json', f_serialisation_tests_token_generated_json],
]
